---
title: "p8105_hw6_zw2541"
author: "Zixu_Wang"
date: "11/22/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
```

## Problem 1

### Read and clean the data

```{r}
homicides = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    solved = as.factor(ifelse(disposition %in% c("Closed without arrest", "Open/No arrest"), 0, 1))) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) %>% 
  mutate(
    victim_race = ifelse(victim_race == "White", "White", "non-White"),
    victim_race = factor(victim_race, levels = c("White", "non-White")),
    victim_age = as.numeric(victim_age))
```

### Fit a logistic regression model

```{r}
lm_baltimore =
  homicides %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ victim_sex + victim_race + victim_age, family = binomial, data = .)

lm_baltimore %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(odds_ratio = exp(estimate),
         conf_low = exp(conf.low),
         conf_high = exp(conf.high)) %>% 
  select(term, odds_ratio, conf_low, conf_high) %>% 
  filter(term == "victim_racenon-White") %>% 
  knitr::kable(digits = 3)
```

The estimate of the adjusted odds ratio for solving homicides comparing non-white victims to white victims is 0.441 (keeping all other variables fixed), and the 95% confidence interval is (0.312, 0.620).

### Run glm for each of the cities 

```{r, warning = FALSE}
estimate_ci =   
  homicides %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(lm_everycity = map(data, ~glm(solved ~ victim_sex + victim_race + victim_age, family = binomial, data = .x)),
         lm_everycity_ci = map(lm_everycity, broom::confint_tidy),
         lm_everycity = map(lm_everycity, broom::tidy)) %>%
  select(-data) %>% 
  unnest() %>% 
  mutate(odds_ratio = exp(estimate),
         conf_low = exp(conf.low),
         conf_high = exp(conf.high)) %>% 
  filter(term == "victim_racenon-White") %>%
  select(city_state, odds_ratio, conf_low, conf_high)

estimate_ci 
```

### Create the plot

```{r}
estimate_ci %>% 
  mutate(city_state = fct_reorder(city_state, odds_ratio)) %>% 
  ggplot(aes(x = city_state, y = odds_ratio)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
        title = "the Estimate Odds Ratio and Confidence Interval of Each City",
        x = "Odds Ratio",
        y = "City, State")
```



## Problem 2

### Read and clean the data

```{r}
birthweight = read_csv("data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = as.factor(babysex), 
    frace = as.factor(frace), 
    malform = as.factor(malform), 
    mrace = as.factor(mrace)
  )

# check for missing data
sum(is.na(birthweight))
```

