p8105\_hw6\_zw2541
================
Zixu\_Wang
11/22/2018

Problem 1
---------

### Read and clean the data

``` r
homicides = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    solved = as.factor(ifelse(disposition %in% c("Closed without arrest", "Open/No arrest"), 0, 1))) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) %>% 
  mutate(
    victim_race = ifelse(victim_race == "White", "White", "non-White"),
    victim_race = factor(victim_race, levels = c("White", "non-White")),
    victim_age = as.numeric(victim_age))
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_integer(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_character(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

    ## Warning in evalq(as.numeric(victim_age), <environment>): NAs introduced by
    ## coercion

### Fit a logistic regression model

``` r
lm_baltimore =
  homicides %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ victim_sex + victim_race + victim_age, family = binomial, data = .)

lm_baltimore %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(odds_ratio = exp(estimate),
         conf_low = exp(conf.low),
         conf_high = exp(conf.high)) %>% 
  select(term, odds_ratio, conf_low, conf_high) %>% 
  filter(term == "victim_racenon-White") %>% 
  knitr::kable(digits = 3)
```

| term                  |  odds\_ratio|  conf\_low|  conf\_high|
|:----------------------|------------:|----------:|-----------:|
| victim\_racenon-White |        0.441|      0.312|        0.62|

The estimate of the adjusted odds ratio for solving homicides comparing non-white victims to white victims is 0.441 (keeping all other variables fixed), and the 95% confidence interval is (0.312, 0.620).

### Run glm for each of the cities

``` r
estimate_ci =   
  homicides %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(lm_everycity = map(data, ~glm(solved ~ victim_sex + victim_race + victim_age, family = binomial, data = .x)),
         lm_everycity_ci = map(lm_everycity, broom::confint_tidy),
         lm_everycity = map(lm_everycity, broom::tidy)) %>%
  select(-data) %>% 
  unnest() %>% 
  mutate(odds_ratio = exp(estimate),
         conf_low = exp(conf.low),
         conf_high = exp(conf.high)) %>% 
  filter(term == "victim_racenon-White") %>%
  select(city_state, odds_ratio, conf_low, conf_high)

estimate_ci 
```

    ## # A tibble: 47 x 4
    ##    city_state      odds_ratio conf_low conf_high
    ##    <chr>                <dbl>    <dbl>     <dbl>
    ##  1 Albuquerque, NM      0.741   0.449      1.22 
    ##  2 Atlanta, GA          0.753   0.424      1.30 
    ##  3 Baltimore, MD        0.441   0.312      0.620
    ##  4 Baton Rouge, LA      0.668   0.304      1.41 
    ##  5 Birmingham, AL       1.04    0.612      1.75 
    ##  6 Boston, MA           0.115   0.0425     0.259
    ##  7 Buffalo, NY          0.390   0.210      0.710
    ##  8 Charlotte, NC        0.558   0.313      0.951
    ##  9 Chicago, IL          0.562   0.432      0.734
    ## 10 Cincinnati, OH       0.318   0.180      0.541
    ## # ... with 37 more rows

### Create the plot

``` r
estimate_ci %>% 
  mutate(city_state = fct_reorder(city_state, odds_ratio)) %>% 
  ggplot(aes(x = city_state, y = odds_ratio)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
        title = "the Estimate Odds Ratio and Confidence Interval of Each City",
        x = "Odds Ratio",
        y = "City, State")
```

![](p8105_hw6_zw2541_files/figure-markdown_github/unnamed-chunk-4-1.png)

Problem 2
---------

### Read and clean the data

``` r
birthweight = read_csv("data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = as.factor(babysex), 
    frace = as.factor(frace), 
    malform = as.factor(malform), 
    mrace = as.factor(mrace)
  )
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_integer(),
    ##   gaweeks = col_double(),
    ##   ppbmi = col_double(),
    ##   smoken = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
# check for missing data
sum(is.na(birthweight))
```

    ## [1] 0
